var width = 5;
var height = 10;
var area = width * height;
console.log('area:', area);
console.log('type of area:', typeof area);
var bill = 20;
var payment = 30;
var change = payment - bill;
console.log('change:', change);
console.log('type of change:', typeof change);
var quizzes = 5;
var midterm = 10;
var final = 20;
var grade = (quizzes + midterm + final) / 2;
console.log('grade:', grade);
console.log('type of grade:', typeof grade);
var firstName = 'Chris';
var lastName = 'Tran';
var fullName = firstName + ' ' + lastName;
console.log('fullName:', fullName);
console.log('type of fullName:', typeof fullName);
var ph = 5;
var isAcidic = ph < 7;
console.log('isAcidic:', isAcidic);
console.log('type of isAcidic:', typeof isAcidic);
var headCount = 10;
var isSparta = headCount === 300;
console.log('isSparta:', isSparta);
console.log('type of isSparta:', typeof isSparta);
var motto = fullName;
motto = motto + ' ' + 'is the GOAT';
console.log('motto:', motto);
console.log('type of motto:', typeof motto);
